//+------------------------------------------------------------------+
//|                                          XAUUSD_MultiStrategy_EA.mq5 |
//|                                    Generated by Elite Quant Trader |
//|                                                                  |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, Elite Quant Trader"
#property link      ""
#property version   "1.01"

//+------------------------------------------------------------------+
//| Input Parameters                                                 |
//+------------------------------------------------------------------+
input int      MagicNumber = 123456;            // EA Magic Number
input bool     AutoMode = true;                 // Enable Auto Mode Switching
input int      StrategyMode = 1;                // Manual Mode (1-AggrScalp,2-SMC,3-Sniper) if AutoMode=false
input double   RiskPerTrade = 1.0;              // Risk per trade (% of balance)
input int      MaxTrades = 3;                   // Maximum concurrent trades
input double   DailyProfitTarget = 0;            // Daily profit target (%), 0 = no limit
input double   DailyLossLimit = 0;               // Daily loss limit (%), 0 = no limit
input bool     SpreadFilterEnabled = true;       // Enable spread filter
input double   MaxSpreadPoints = 30;             // Max allowed spread (points, 1 point = _Point)
input int      ATRPeriod = 14;                  // ATR period for volatility
input double   ScoreThresholdInit = 0.7;        // Initial AI score threshold (0-1)
input bool     EnableAdaptiveLearning = true;    // Enable adaptive learning
input bool     EnableTradeManagement = true;     // Enable BE/Partial/Trailing
input bool     EnableProfitProtection = true;    // Enable profit protection rules
input bool     DebugMode = false;                // Print debug logs

//+------------------------------------------------------------------+
//| Global Variables                                                 |
//+------------------------------------------------------------------+
datetime lastBarTime = 0;
double   dailyProfit = 0;
double   dailyPeak = 0;
int      consecutiveWins = 0;
bool     stopTrading = false;
double   currentRiskMultiplier = 1.0;
double   adaptiveScoreThreshold = 0.7;

// Trade history for adaptive learning
struct TradeRecord {
   double score;
   bool   win;
   double lot;
};
TradeRecord tradeHistory[50];
int historyIndex = 0;
int historyCount = 0;

//+------------------------------------------------------------------+
//| Enums and Structures                                             |
//+------------------------------------------------------------------+
enum ENUM_MARKET_STATE {
   STATE_TREND_UP,
   STATE_TREND_DOWN,
   STATE_RANGE
};

enum ENUM_VOLATILITY_LEVEL {
   VOL_LOW,
   VOL_MEDIUM,
   VOL_HIGH
};

struct TradeSignal {
   int direction;   // 1 = buy, -1 = sell
   double entryPrice;
   double slPrice;
   double tpPrice;
   int slPoints;    // in points (absolute)
   int tpPoints;
   // Additional for scoring
   double structureScore;
   double liquidityScore;
   double volumeScore;
   double volatilityScore;
   double entryPrecisionScore;
};

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   Print("EA initialized. XAUUSD M1 Multi-Strategy EA ready.");
   lastBarTime = 0;
   dailyProfit = 0;
   dailyPeak = 0;
   consecutiveWins = 0;
   stopTrading = false;
   currentRiskMultiplier = 1.0;
   adaptiveScoreThreshold = ScoreThresholdInit;
   historyIndex = 0;
   historyCount = 0;
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   Print("EA deinitialized. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Helper Functions                                                 |
//+------------------------------------------------------------------+
bool isNewBar() {
   datetime curTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(lastBarTime != curTime) {
      lastBarTime = curTime;
      return true;
   }
   return false;
}

int getCurrentSpreadPoints() {
   return (int)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
}

int CountOpenPositions() {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket)) {
         if(PositionGetInteger(POSITION_MAGIC) == MagicNumber && PositionGetString(POSITION_SYMBOL) == _Symbol)
            count++;
      }
   }
   return count;
}

bool updateDailyStats() {
   static datetime lastDay = 0;
   datetime today = iTime(_Symbol, PERIOD_D1, 0);
   if(lastDay != today) {
      dailyProfit = 0;
      dailyPeak = 0;
      consecutiveWins = 0;
      currentRiskMultiplier = 1.0;
      lastDay = today;
      return true;
   }
   dailyProfit = (AccountInfoDouble(ACCOUNT_EQUITY) - AccountInfoDouble(ACCOUNT_BALANCE)) / AccountInfoDouble(ACCOUNT_BALANCE);
   if(dailyProfit > dailyPeak) dailyPeak = dailyProfit;
   return false;
}

//+------------------------------------------------------------------+
//| Volatility Detection                                             |
//+------------------------------------------------------------------+
ENUM_VOLATILITY_LEVEL GetVolatilityLevel() {
   double atr[];
   ArraySetAsSeries(atr, true);
   CopyBuffer(iATR(_Symbol, PERIOD_CURRENT, ATRPeriod), 0, 0, 100, atr);
   if(ArraySize(atr) < 20) return VOL_MEDIUM;
   
   double avgATR = 0;
   for(int i = 1; i <= 20; i++) avgATR += atr[i];
   avgATR /= 20;
   double currentATR = atr[0];
   
   if(currentATR < avgATR * 0.7) return VOL_LOW;
   if(currentATR > avgATR * 1.3) return VOL_HIGH;
   return VOL_MEDIUM;
}

//+------------------------------------------------------------------+
//| Market State Detection                                           |
//+------------------------------------------------------------------+
ENUM_MARKET_STATE GetMarketState() {
   double maFast[], maSlow[];
   ArraySetAsSeries(maFast, true);
   ArraySetAsSeries(maSlow, true);
   CopyBuffer(iMA(_Symbol, PERIOD_CURRENT, 10, 0, MODE_SMA, PRICE_CLOSE), 0, 0, 3, maFast);
   CopyBuffer(iMA(_Symbol, PERIOD_CURRENT, 30, 0, MODE_SMA, PRICE_CLOSE), 0, 0, 3, maSlow);
   if(ArraySize(maFast) < 3 || ArraySize(maSlow) < 3) return STATE_RANGE;
   
   double adx[];
   ArraySetAsSeries(adx, true);
   CopyBuffer(iADX(_Symbol, PERIOD_CURRENT, 14), 0, 0, 2, adx);
   double adxVal = (ArraySize(adx) > 0) ? adx[0] : 20;
   
   if(adxVal > 25) {
      if(maFast[0] > maSlow[0] && maFast[1] > maSlow[1])
         return STATE_TREND_UP;
      if(maFast[0] < maSlow[0] && maFast[1] < maSlow[1])
         return STATE_TREND_DOWN;
   }
   return STATE_RANGE;
}

//+------------------------------------------------------------------+
//| Auto Mode Selection                                              |
//+------------------------------------------------------------------+
int GetAutoMode(ENUM_MARKET_STATE marketState, ENUM_VOLATILITY_LEVEL volLevel) {
   if((marketState == STATE_TREND_UP || marketState == STATE_TREND_DOWN) && volLevel == VOL_HIGH)
      return 1;
   if((marketState == STATE_TREND_UP || marketState == STATE_TREND_DOWN) && volLevel != VOL_LOW)
      return 2;
   return 3;
}

//+------------------------------------------------------------------+
//| MODE 1: Aggressive Scalping                                      |
//+------------------------------------------------------------------+
bool GetAggressiveScalpingSignal(TradeSignal &signal) {
   double high[], low[], close[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   ArraySetAsSeries(close, true);
   CopyHigh(_Symbol, PERIOD_CURRENT, 0, 10, high);
   CopyLow(_Symbol, PERIOD_CURRENT, 0, 10, low);
   CopyClose(_Symbol, PERIOD_CURRENT, 0, 10, close);
   if(ArraySize(high) < 6) return false;
   
   double rangeHigh = high[1];
   double rangeLow = low[1];
   for(int i=2; i<=5; i++) {
      if(high[i] > rangeHigh) rangeHigh = high[i];
      if(low[i] < rangeLow) rangeLow = low[i];
   }
   
   bool bullishBreak = close[0] > rangeHigh && close[1] <= rangeHigh;
   bool bearishBreak = close[0] < rangeLow && close[1] >= rangeLow;
   if(!bullishBreak && !bearishBreak) return false;
   
   bool retest = false;
   if(bullishBreak && low[0] <= rangeHigh + (rangeHigh-rangeLow)*0.2 && close[0] > rangeHigh)
      retest = true;
   if(bearishBreak && high[0] >= rangeLow - (rangeHigh-rangeLow)*0.2 && close[0] < rangeLow)
      retest = true;
   if(!retest) return false;
   
   double body = MathAbs(close[0] - iOpen(_Symbol, PERIOD_CURRENT, 0));
   double avgBody = MathAbs(iClose(_Symbol, PERIOD_CURRENT, 1) - iOpen(_Symbol, PERIOD_CURRENT, 1));
   if(body < avgBody * 1.2) return false;
   
   long volume[];
   ArraySetAsSeries(volume, true);
   CopyTickVolume(_Symbol, PERIOD_CURRENT, 0, 10, volume);
   if(ArraySize(volume) < 10) return false;
   double avgVol = 0;
   for(int i=1; i<=5; i++) avgVol += volume[i];
   avgVol /= 5;
   if(volume[0] < avgVol * 1.5) return false;
   
   ENUM_VOLATILITY_LEVEL vol = GetVolatilityLevel();
   int slPoints = 50;
   int tpPoints = 100;
   if(vol == VOL_LOW) { slPoints = 40; tpPoints = 70; }
   if(vol == VOL_HIGH) { slPoints = 120; tpPoints = 200; }
   
   signal.direction = bullishBreak ? 1 : -1;
   signal.entryPrice = (signal.direction == 1) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   if(signal.direction == 1) {
      signal.slPrice = signal.entryPrice - slPoints * point;
      signal.tpPrice = signal.entryPrice + tpPoints * point;
   } else {
      signal.slPrice = signal.entryPrice + slPoints * point;
      signal.tpPrice = signal.entryPrice - tpPoints * point;
   }
   signal.slPoints = slPoints;
   signal.tpPoints = tpPoints;
   
   signal.structureScore = 0.8;
   signal.liquidityScore = 0.6;
   signal.volumeScore = (volume[0] / avgVol) > 2.0 ? 0.9 : 0.7;
   signal.volatilityScore = (vol == VOL_HIGH) ? 0.9 : (vol == VOL_MEDIUM) ? 0.6 : 0.4;
   signal.entryPrecisionScore = 0.8;
   return true;
}

//+------------------------------------------------------------------+
//| MODE 2: SMC / ICT                                                |
//+------------------------------------------------------------------+
bool GetSMCSignal(TradeSignal &signal) {
   double high[], low[], close[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   ArraySetAsSeries(close, true);
   CopyHigh(_Symbol, PERIOD_CURRENT, 0, 20, high);
   CopyLow(_Symbol, PERIOD_CURRENT, 0, 20, low);
   CopyClose(_Symbol, PERIOD_CURRENT, 0, 20, close);
   if(ArraySize(high) < 15) return false;
   
   int swingHighIdx = -1, swingLowIdx = -1;
   for(int i=5; i<15; i++) {
      if(high[i] > high[i-1] && high[i] > high[i-2] && high[i] > high[i+1] && high[i] > high[i+2])
         swingHighIdx = i;
      if(low[i] < low[i-1] && low[i] < low[i-2] && low[i] < low[i+1] && low[i] < low[i+2])
         swingLowIdx = i;
   }
   if(swingHighIdx == -1 && swingLowIdx == -1) return false;
   
   bool sweepUp = (close[0] > high[swingHighIdx] && close[1] <= high[swingHighIdx]);
   bool sweepDown = (close[0] < low[swingLowIdx] && close[1] >= low[swingLowIdx]);
   if(!sweepUp && !sweepDown) return false;
   
   bool bullishOB = false, bearishOB = false;
   if(sweepUp) {
      for(int i=2; i<=5; i++) {
         double o = iOpen(_Symbol, PERIOD_CURRENT, i);
         double c = iClose(_Symbol, PERIOD_CURRENT, i);
         if(c > o && (c - o) > (high[i] - low[i]) * 0.5) {
            bullishOB = true;
            break;
         }
      }
   } else {
      for(int i=2; i<=5; i++) {
         double o = iOpen(_Symbol, PERIOD_CURRENT, i);
         double c = iClose(_Symbol, PERIOD_CURRENT, i);
         if(c < o && (o - c) > (high[i] - low[i]) * 0.5) {
            bearishOB = true;
            break;
         }
      }
   }
   if((sweepUp && !bullishOB) || (sweepDown && !bearishOB)) return false;
   
   double fvg = 0;
   if(sweepUp) {
      double prevHigh = high[1], prevLow = low[1];
      if(close[0] > prevHigh && low[0] > prevHigh) fvg = 1;
   } else {
      double prevHigh = high[1], prevLow = low[1];
      if(close[0] < prevLow && high[0] < prevLow) fvg = 1;
   }
   if(fvg == 0) return false;
   
   double fibLevel = 0.618;
   double entryPrice = sweepUp ? low[0] + (high[0]-low[0])*0.382 : high[0] - (high[0]-low[0])*0.382;
   double slPrice = sweepUp ? low[swingLowIdx] - (high[swingHighIdx]-low[swingLowIdx])*0.1 : high[swingHighIdx] + (high[swingHighIdx]-low[swingLowIdx])*0.1;
   double tpPrice = sweepUp ? high[swingHighIdx] + (high[swingHighIdx]-low[swingLowIdx])*0.5 : low[swingLowIdx] - (high[swingHighIdx]-low[swingLowIdx])*0.5;
   
   int slPoints = (int)(MathAbs(slPrice - entryPrice) / SymbolInfoDouble(_Symbol, SYMBOL_POINT));
   int tpPoints = (int)(MathAbs(tpPrice - entryPrice) / SymbolInfoDouble(_Symbol, SYMBOL_POINT));
   if(tpPoints < slPoints * 2) return false;
   
   signal.direction = sweepUp ? 1 : -1;
   signal.entryPrice = entryPrice;
   signal.slPrice = slPrice;
   signal.tpPrice = tpPrice;
   signal.slPoints = slPoints;
   signal.tpPoints = tpPoints;
   
   signal.structureScore = 0.9;
   signal.liquidityScore = 0.85;
   signal.volumeScore = 0.7;
   signal.volatilityScore = (GetVolatilityLevel() == VOL_HIGH) ? 0.8 : 0.6;
   signal.entryPrecisionScore = 0.75;
   return true;
}

//+------------------------------------------------------------------+
//| MODE 3: Sniper Reversal                                          |
//+------------------------------------------------------------------+
bool GetSniperReversalSignal(TradeSignal &signal) {
   double high[], low[], close[], openArr[];
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   ArraySetAsSeries(close, true);
   ArraySetAsSeries(openArr, true);
   CopyHigh(_Symbol, PERIOD_CURRENT, 0, 5, high);
   CopyLow(_Symbol, PERIOD_CURRENT, 0, 5, low);
   CopyClose(_Symbol, PERIOD_CURRENT, 0, 5, close);
   CopyOpen(_Symbol, PERIOD_CURRENT, 0, 5, openArr);
   if(ArraySize(high) < 3) return false;
   
   double body = MathAbs(close[0] - openArr[0]);
   double upperWick = high[0] - MathMax(close[0], openArr[0]);
   double lowerWick = MathMin(close[0], openArr[0]) - low[0];
   bool bullishReversal = (lowerWick > body * 2 && close[0] > openArr[0] && close[0] > low[0] + (high[0]-low[0])*0.3);
   bool bearishReversal = (upperWick > body * 2 && close[0] < openArr[0] && close[0] < high[0] - (high[0]-low[0])*0.3);
   if(!bullishReversal && !bearishReversal) return false;
   
   double level = 0;
   if(bullishReversal) {
      double support = low[ArrayMinimum(low, 1, 10)];
      if(close[0] <= support + (high[0]-low[0])*0.5) level = support;
      else return false;
   } else {
      double resistance = high[ArrayMaximum(high, 1, 10)];
      if(close[0] >= resistance - (high[0]-low[0])*0.5) level = resistance;
      else return false;
   }
   
   long volume[];
   ArraySetAsSeries(volume, true);
   CopyTickVolume(_Symbol, PERIOD_CURRENT, 0, 10, volume);
   if(ArraySize(volume) < 6) return false;
   double avgVol = (volume[1]+volume[2]+volume[3])/3.0;
   bool volClimax = (volume[0] > avgVol * 1.8 && volume[1] < volume[0] * 0.7);
   if(!volClimax) return false;
   
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   int slPoints = (int)(MathAbs(level - (bullishReversal ? low[0] : high[0])) / point) + 10;
   int tpPoints = slPoints * 3;
   if(bullishReversal) {
      signal.direction = 1;
      signal.entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      signal.slPrice = low[0] - slPoints * point;
      signal.tpPrice = signal.entryPrice + tpPoints * point;
   } else {
      signal.direction = -1;
      signal.entryPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      signal.slPrice = high[0] + slPoints * point;
      signal.tpPrice = signal.entryPrice - tpPoints * point;
   }
   signal.slPoints = slPoints;
   signal.tpPoints = tpPoints;
   
   signal.structureScore = 0.85;
   signal.liquidityScore = 0.7;
   signal.volumeScore = (volume[0]/avgVol) > 2.5 ? 0.95 : 0.8;
   signal.volatilityScore = (GetVolatilityLevel() == VOL_LOW) ? 0.9 : 0.5;
   signal.entryPrecisionScore = 0.9;
   return true;
}

//+------------------------------------------------------------------+
//| AI Scoring System                                                |
//+------------------------------------------------------------------+
double ComputeAIScore(TradeSignal &signal, ENUM_MARKET_STATE marketState, ENUM_VOLATILITY_LEVEL volLevel) {
   double wStruct = 0.25, wLiq = 0.25, wVol = 0.20, wVolat = 0.15, wEntry = 0.15;
   double structScore = signal.structureScore;
   double liqScore = signal.liquidityScore;
   double volScore = signal.volumeScore;
   double volatScore = signal.volatilityScore;
   double entryScore = signal.entryPrecisionScore;
   
   if(marketState == STATE_TREND_UP || marketState == STATE_TREND_DOWN) {
      if(signal.direction == 1 && marketState == STATE_TREND_UP) structScore += 0.1;
      if(signal.direction == -1 && marketState == STATE_TREND_DOWN) structScore += 0.1;
   } else {
      if(signal.direction == 1) liqScore += 0.1;
   }
   
   structScore = MathMin(1.0, MathMax(0.0, structScore));
   liqScore = MathMin(1.0, MathMax(0.0, liqScore));
   volScore = MathMin(1.0, MathMax(0.0, volScore));
   volatScore = MathMin(1.0, MathMax(0.0, volatScore));
   entryScore = MathMin(1.0, MathMax(0.0, entryScore));
   
   double total = wStruct*structScore + wLiq*liqScore + wVol*volScore + wVolat*volatScore + wEntry*entryScore;
   return total;
}

//+------------------------------------------------------------------+
//| Lot Size Calculation                                             |
//+------------------------------------------------------------------+
double CalculateLotSize(int slPoints) {
   double riskPercent = RiskPerTrade / 100.0;
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskMoney = balance * riskPercent;
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double slValue = slPoints * point;
   double lot = riskMoney / (slValue * tickValue);
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lot = MathFloor(lot / step) * step;
   return lot;
}

//+------------------------------------------------------------------+
//| Execute Trade                                                    |
//+------------------------------------------------------------------+
bool ExecuteTrade(TradeSignal &signal, double lot, double score) {
   MqlTradeRequest req = {};
   MqlTradeResult res = {};
   req.action = TRADE_ACTION_DEAL;
   req.symbol = _Symbol;
   req.volume = lot;
   req.type = (signal.direction == 1) ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
   req.price = (signal.direction == 1) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   req.sl = signal.slPrice;
   req.tp = signal.tpPrice;
   req.deviation = 10;
   req.magic = MagicNumber;
   req.comment = "MultiStrategy";
   
   if(OrderSend(req, res)) {
      if(DebugMode) Print("Order sent: ", res.comment, " | Ticket: ", res.order);
      return true;
   } else {
      Print("Order failed: ", res.retcode);
      return false;
   }
}

//+------------------------------------------------------------------+
//| Position Management (Trailing, Breakeven, Partial)              |
//+------------------------------------------------------------------+
void ManageOpenPositions() {
   if(!EnableTradeManagement) return;
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(!PositionSelectByTicket(ticket)) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      
      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double sl = PositionGetDouble(POSITION_SL);
      double tp = PositionGetDouble(POSITION_TP);
      double currentPrice = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_BID) : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double risk = MathAbs(openPrice - sl);
      double profitPoints = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? (currentPrice - openPrice) : (openPrice - currentPrice);
      profitPoints /= SymbolInfoDouble(_Symbol, SYMBOL_POINT);
      double riskPoints = risk / SymbolInfoDouble(_Symbol, SYMBOL_POINT);
      
      // Breakeven at 1R
      if(profitPoints >= riskPoints && sl == openPrice) {
         MqlTradeRequest req = {};
         MqlTradeResult res = {};
         req.action = TRADE_ACTION_SLTP;
         req.position = ticket;
         req.sl = openPrice;
         req.tp = tp;
         if(OrderSend(req, res) && DebugMode)
            Print("Breakeven set for ticket ", ticket);
      }
      
      // Partial close at 1.5R (close half)
      if(profitPoints >= riskPoints * 1.5) {
         double currentVol = PositionGetDouble(POSITION_VOLUME);
         double halfVol = currentVol / 2.0;
         if(halfVol >= SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN)) {
            MqlTradeRequest req = {};
            MqlTradeResult res = {};
            req.action = TRADE_ACTION_DEAL;
            req.symbol = _Symbol;
            req.volume = halfVol;
            req.type = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? ORDER_TYPE_SELL : ORDER_TYPE_BUY;
            req.position = ticket;
            req.price = currentPrice;
            req.deviation = 10;
            req.magic = MagicNumber;
            if(OrderSend(req, res) && DebugMode)
               Print("Partial close at 1.5R for ticket ", ticket);
         }
      }
      
      // Trailing stop: ATR based
      double atr = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
      double trailPoints = atr / SymbolInfoDouble(_Symbol, SYMBOL_POINT) * 0.5;
      double newSL = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? currentPrice - trailPoints * SymbolInfoDouble(_Symbol, SYMBOL_POINT) : currentPrice + trailPoints * SymbolInfoDouble(_Symbol, SYMBOL_POINT);
      if((PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY && newSL > sl) ||
         (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_SELL && newSL < sl)) {
         MqlTradeRequest req = {};
         MqlTradeResult res = {};
         req.action = TRADE_ACTION_SLTP;
         req.position = ticket;
         req.sl = newSL;
         req.tp = tp;
         OrderSend(req, res);
      }
   }
}

//+------------------------------------------------------------------+
//| Profit Protection & Adaptive Learning (called after trade close)|
//+------------------------------------------------------------------+
void UpdateProfitProtection(double tradeProfit) {
   if(!EnableProfitProtection) return;
   double currentProfit = dailyProfit;
   if(currentProfit >= 0.03) currentRiskMultiplier = 0.5;
   if(currentProfit >= 0.05) currentRiskMultiplier = 0.3;
   if(dailyPeak - currentProfit >= 0.02) stopTrading = true;
}

void UpdateAdaptiveLearning(double score, bool win, double lot) {
   if(!EnableAdaptiveLearning) return;
   tradeHistory[historyIndex].score = score;
   tradeHistory[historyIndex].win = win;
   tradeHistory[historyIndex].lot = lot;
   historyIndex = (historyIndex + 1) % 50;
   if(historyCount < 50) historyCount++;
   
   int lowScoreWins = 0, lowScoreTotal = 0;
   int highScoreWins = 0, highScoreTotal = 0;
   for(int i=0; i<historyCount; i++) {
      if(tradeHistory[i].score < 0.6) {
         lowScoreTotal++;
         if(tradeHistory[i].win) lowScoreWins++;
      } else if(tradeHistory[i].score > 0.8) {
         highScoreTotal++;
         if(tradeHistory[i].win) highScoreWins++;
      }
   }
   if(lowScoreTotal >= 5 && (double)lowScoreWins/lowScoreTotal < 0.4)
      adaptiveScoreThreshold = MathMin(0.85, adaptiveScoreThreshold + 0.02);
   if(highScoreTotal >= 5 && (double)highScoreWins/highScoreTotal > 0.7)
      currentRiskMultiplier = MathMin(1.5, currentRiskMultiplier + 0.05);
   else if(highScoreTotal >= 5 && (double)highScoreWins/highScoreTotal < 0.5)
      currentRiskMultiplier = MathMax(0.5, currentRiskMultiplier - 0.03);
}

//+------------------------------------------------------------------+
//| OnTradeTransaction - Capture closed trades for adaptive learning|
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result) {
   if(trans.type == TRADE_TRANSACTION_DEAL_ADD) {
      long dealTicket = trans.deal;
      HistoryDealSelect(dealTicket);
      long dealType = HistoryDealGetInteger(dealTicket, DEAL_TYPE);
      if(dealType == DEAL_TYPE_BUY || dealType == DEAL_TYPE_SELL) {
         double profit = HistoryDealGetDouble(dealTicket, DEAL_PROFIT);
         if(profit != 0) {
            // We need to retrieve stored score for this trade. For simplicity, we don't store per-ticket score.
            // Here we can just update consecutive wins/losses and profit protection.
            if(profit > 0) consecutiveWins++;
            else consecutiveWins = 0;
            UpdateProfitProtection(profit);
            if(consecutiveWins >= 3) currentRiskMultiplier = MathMax(0.5, currentRiskMultiplier - 0.1);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Main OnTick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
   // First, manage existing positions
   ManageOpenPositions();
   
   // New bar only for signal generation
   if(!isNewBar()) return;
   
   // Update daily stats and check limits
   if(updateDailyStats()) {
      if(DailyProfitTarget > 0 && dailyProfit >= DailyProfitTarget/100.0) {
         if(DebugMode) Print("Daily profit target reached. Stop trading.");
         stopTrading = true;
      }
      if(DailyLossLimit > 0 && dailyProfit <= -DailyLossLimit/100.0) {
         if(DebugMode) Print("Daily loss limit reached. Stop trading.");
         stopTrading = true;
      }
   }
   
   if(stopTrading) return;
   
   if(SpreadFilterEnabled && getCurrentSpreadPoints() > MaxSpreadPoints) {
      if(DebugMode) Print("Spread too high: ", getCurrentSpreadPoints(), " points. Waiting.");
      return;
   }
   
   if(CountOpenPositions() >= MaxTrades) return;
   
   ENUM_MARKET_STATE marketState = GetMarketState();
   ENUM_VOLATILITY_LEVEL volLevel = GetVolatilityLevel();
   int activeMode;
   
   if(AutoMode) {
      activeMode = GetAutoMode(marketState, volLevel);
      if(DebugMode) Print("Auto Mode selected: ", activeMode);
   } else {
      activeMode = StrategyMode;
      if(DebugMode) Print("Manual Mode: ", activeMode);
   }
   
   TradeSignal signal;
   ZeroMemory(signal);
   bool hasSignal = false;
   
   switch(activeMode) {
      case 1: hasSignal = GetAggressiveScalpingSignal(signal); break;
      case 2: hasSignal = GetSMCSignal(signal); break;
      case 3: hasSignal = GetSniperReversalSignal(signal); break;
      default: return;
   }
   
   if(!hasSignal) return;
   
   double score = ComputeAIScore(signal, marketState, volLevel);
   if(DebugMode) Print("AI Score: ", score, " | Threshold: ", adaptiveScoreThreshold);
   if(score < adaptiveScoreThreshold) return;
   
   double lot = CalculateLotSize(signal.slPoints);
   lot *= currentRiskMultiplier;
   lot = MathMax(lot, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
   lot = MathMin(lot, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX));
   
   if(ExecuteTrade(signal, lot, score)) {
      if(DebugMode) Print("Trade executed. Mode: ", activeMode, " Score: ", score, " Lot: ", lot);
   }
}
//+------------------------------------------------------------------+